/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-fixed": "#ceeda0",
        "on-primary-container": "#9fbd75",
        "background": "#fbf9f0",
        "primary-fixed-dim": "#b2d187",
        "surface-container-low": "#f6f4eb",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#d4eab8",
        "on-primary-fixed": "#112000",
        "secondary-fixed-dim": "#b8ce9e",
        "surface-tint": "#4d6629",
        "secondary-container": "#d1e7b5",
        "on-secondary": "#ffffff",
        "tertiary": "#253225",
        "surface-container-highest": "#e4e3da",
        "surface": "#fbf9f0",
        "error-container": "#ffdad6",
        "on-secondary-container": "#556941",
        "inverse-primary": "#b2d187",
        "primary-container": "#344c11",
        "inverse-surface": "#30312b",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#3b493a",
        "surface-dim": "#dcdad1",
        "primary": "#1f3500",
        "on-background": "#1b1c17",
        "secondary": "#51643d",
        "error": "#ba1a1a",
        "on-error-container": "#93000a",
        "on-surface": "#1b1c17",
        "on-primary": "#ffffff",
        "surface-container-high": "#eae8df",
        "surface-container": "#f0eee5",
        "surface-bright": "#fbf9f0",
        "outline-variant": "#c5c8b8",
        "outline": "#75796b",
        "surface-variant": "#e4e3da",
        "on-surface-variant": "#44483c",
        "tertiary-fixed": "#d7e7d3",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "20px",
        "section-gap": "80px",
        "margin-desktop": "64px",
        "gutter": "24px",
      },
      fontFamily: {
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "button-text": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Literata", "serif"],
        "headline-lg-mobile": ["Literata", "serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-xl": ["Literata", "serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Literata", "serif"],
      },
      fontSize: {
        "body-lg": ["20px", { lineHeight: "1.6", fontWeight: "400" }],
        "button-text": ["16px", { lineHeight: "1.0", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.01em", fontWeight: "800" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "800" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "700" }],
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "900" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "700" }],
      },
      keyframes: {
        float: { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-14px)" } },
        floatRotate: { "0%,100%": { transform: "translateY(0) rotate(-1deg)" }, "50%": { transform: "translateY(-10px) rotate(1deg)" } },
        bellRing: {
          "0%": { transform: "rotate(0)" },
          "10%": { transform: "rotate(20deg) scale(1.1)" },
          "20%": { transform: "rotate(-18deg) scale(1.1)" },
          "30%": { transform: "rotate(15deg)" },
          "50%": { transform: "rotate(-8deg)" },
          "70%": { transform: "rotate(4deg)" },
          "100%": { transform: "rotate(0)" },
        },
        fadeUp: { from: { opacity: "0", transform: "translateY(36px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        slideInLeft: { from: { opacity: "0", transform: "translateX(-60px) rotate(-4deg)" }, to: { opacity: "1", transform: "translateX(0) rotate(0)" } },
        slideInRight: { from: { opacity: "0", transform: "translateX(60px) rotate(4deg)" }, to: { opacity: "1", transform: "translateX(0) rotate(0)" } },
        roadmapSlide: { from: { opacity: "0", transform: "translateX(40px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        barFill: { from: { width: "0%" }, to: { width: "var(--target-w)" } },
        ping: { "75%,100%": { transform: "scale(2)", opacity: "0" } },
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-2": "floatRotate 7s ease-in-out 1s infinite",
        "float-3": "float 5s ease-in-out 2s infinite",
        "bell-ring": "bellRing 1s cubic-bezier(.36,.07,.19,.97) both",
        "fade-up": "fadeUp 0.8s ease both",
        "slide-left": "slideInLeft 0.75s ease both",
        "slide-right": "slideInRight 0.75s ease both",
        "roadmap-slide": "roadmapSlide 0.5s ease both",
        ping: "ping 1s cubic-bezier(0,0,0.2,1) infinite",
      },
    },
  },
  plugins: [],
};
